### ISSUE TITLE
Unable to download the pre-trained models

### ISSUE THREAD

**Issue by bnaman50** [google-research-datasets/bim#1]
Hey,

I found your paper really interesting and was trying to run the code. In this process, I was not able to download the pre-trained models using your `download_models.sh` script. I would really appreciate if you can provide any guidance regarding this particular issue. 

Here is the screenshot showing that the link is not working. 

![image](https://user-images.githubusercontent.com/5251592/66694999-a9c8f800-ec80-11e9-84b9-337dbb64438e.png)

Thanks, 
Naman

**Comment by SaiSrini** [comment]
The links are dead for me too. Do you have a mirror?

Thanks.

**Comment by sherryy** [comment]
Fixed.
