### ISSUE TITLE
Issue with re-producing results for 10k images

### ISSUE THREAD

**Issue by chirag-agarwall** [google-research-datasets/bim#2]
Hello @sherryy,

Interesting work on creating a new dataset for evaluating interpretability methods.

While running the code for calculating MCS scores on 10k images, I found that the [obj_mask](https://github.com/google-research-datasets/bim/blob/master/bim/attributions.py#L178) (in Line 178 of bim/attributions.py) can only work for indices explicitly from [0, 999]. Whenever we take FLAGS.num_imgs > 1000 it will give an error (because the val_mask is an array of 1000 elements).

![image](https://user-images.githubusercontent.com/12678048/67356825-2ed5cc00-f521-11e9-96c0-abc6e6d4c3a4.png)

This is the modified version of the same which I feel solves the issue.
```
    # Loading val_mask from the data directory
    masks_mat = np.load(tf.gfile.GFile(mask_fpath, 'rb'), allow_pickle=True)
    # Getting obj indices
    obj_inds = [obj_dict[i.split('.')[0].split('-')[0]] for i in img_names]
    # getting indices for a particular object class
    temp_inds = [int(i.split('.')[0][-2:]) for i in img_names]
    obj_masks = [masks_mat[obj_inds[i]*100 + temp_inds[i]]
                     for i, _ in enumerate(img_names)]
```

I would greatly appreciate it if you can provide your comment on this issue as this is very important for my current research.

Thanks,
Chirag

**Comment by sherryy** [comment]
Hi Chirag,

Thanks for the catch. You're right. We launched one job per scene class in the original experiments so the num_imgs is never more than 1000. Do you mind forking the repo and creating a pull request with your change? I looked at your code and it seems correct, but some pieces are missing such as defining the obj_dict.

**Comment by chirag-agarwall** [comment]
Hello @sherryy,

Thanks for your reply. I have made a pull request and committed the changes.
