### ISSUE TITLE
model zip files are corrupt

### ISSUE THREAD

**Issue by arnegevaert** [google-research-datasets/bim#8]
Thank you very much for releasing this project!
I'm having some trouble downloading the models using the `download_models.sh` script as described in the project readme.
Every unzip command gives an `End-of-central-directory signature not found` error, which apparently indicates that the zip files are either corrupt, or part of a multi-part archive. Upon inspection of the downloaded zip files, I noticed that all of them are only 133 bytes in size.

**Comment by sherryy** [comment]
This has been resolved. Models are directly included in the models directory now, though now git clone will take longer. Please re-run download_models.sh now.
